version: '3.6'

services:

  redis:
    image: 'bitnami/redis:latest'

    ports:
      - "6379:6379"

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redisinsights:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - ./data/redisinsight:/db